# Use the official Apache image as the base
FROM httpd:latest

# Copy custom Apache configuration files to the container
COPY ./apache-config/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./apache-config/extra/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

# Copy your web content to the container
COPY ./web-content/ /usr/local/apache2/htdocs/

# Expose port 80 for HTTP traffic
EXPOSE 80


